branch-defaults:
  main:
    environment: dopeticks-dev
environment-defaults:
  dopeticks-dev:
    branch: null
    repository: null
global:
  application_name: dopeticks
  default_ec2_keyname: aws-eb-dope-keypair
  default_platform: Python 3.11 running on 64bit Amazon Linux 2023
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
